### ISSUE TITLE
possible bug when the first OTP is incorrect

### ISSUE THREAD

**Issue by ksyblast** [privacyidea/privacyidea-credential-provider#117]
Hello!

We are suspecting a possible bug in windows credential provider. Please consider the following scenario:

A user logs in to a windows machine, enters his password and then is followed to enter OTP. If a correct OTP value is entered everything is fine and authentication is successful.

However if a wrong OTP is entered a user gets "Response did not match the challenge" error message and is prompted to enter OTP again (in the input a user sees a "One-Time password" message). Entering a correct OTP results in "Wrong OTP pin" error message.

I have performed some debugging and this is what I found:
1. Wrong OTP:
```
[Fri Aug 12 13:35:24.522543 2022] DEBUG:privacyidea.lib.user:Entering get_user_from_param with arguments ({'pass': '123456', 'transaction_id': '08391592998610266892', 'user': 'myuser'},) and keywords {}
...
[Fri Aug 12 13:35:24.855283 2022] DEBUG:privacyidea.lib.auditmodules.base:Entering log with arguments (<privacyidea.lib.auditmodules.sqlaudit.Audit object at 0x7f5c81178b50>, {'info': 'Response did not match the challenge.', 'success': False, 'serial': 'TOTP00144F62', 'token_type': 'totp'}) and keywords {}
```

 2. Correct OTP :
 ```
[Fri Aug 12 13:35:34.086149 2022] DEBUG:privacyidea.lib.user:Entering get_user_from_param with arguments ({'pass': '555915', 'user': 'myuser'},) and keywords {}
...
[Fri Aug 12 13:35:34.440609 2022] [wsgi:error] DEBUG:privacyidea.lib.auditmodules.base:Entering log with arguments (<privacyidea.lib.auditmodules.sqlaudit.Audit object at 0x7f5c835198b0>, {'info': 'wrong otp pin', 'success': False, 'serial': None, 'token_type': None}) and keywords {}
```

Looks like transaction id is missing in the second request and privacyidea cannot link OTP with a password.

Regexp value two_step_send_password is set to 1.

Could you please check if it's a bug or probably point us where the issue could be.

**Comment by nilsbehlen** [comment]
Hi, thanks for reporting. I will look into this tomorrow.

**Comment by nilsbehlen** [comment]
I could not reproduce this problem. If i enter the wrong OTP once and start over again, the new transactionid will be used for the next try.
I used two_step_send_password and set the PIN of the TOTP token to the windows password. Also changed TOTP to be a challenge response token via policy.
You can enable logging in the CP by setting `debug_log` to `1`. This will create a log file on `C:\` where you can see what is sent and what is received as the response (or put it here). If you want to check that the password is sent correctly, you can additionally set `log_sensitive` to `1`.

**Comment by ksyblast** [comment]
Hello!
Thank you for checking that. I will try to explain better to be sure you have checked it in the same way. 
1. a user opens RDP session
2. he enters his password
3. he is promted to enter OTP and he a enters wrong OTP
4. he is prompted to enter OTP again within **the same RDP session**
5. he enters correct OTP
6. he gets wrong OTP pin message

If after p.3 a user reopens RDP session he enters his password and correct OTP again and everything works. We also have two_step_send_password set to 1 and "otppin": "userstore" set in the policy.
I have attached debug logs, could you please check it out.

[debug.txt](https://github.com/privacyidea/privacyidea-credential-provider/files/9432803/debug.txt)

**Comment by nilsbehlen** [comment]
Ok, doing RDP is a bit different and i can confirm the behavior for that. The reason is that when doing RDP, you only trigger the token once when the connection is established. If a wrong OTP is entered, the CP does not reset completly, like it would in a local login, allowing to trigger again to receive a new transactionid. This is because the password has already been verified on the (RDP) starting machine and the authentication package is already complete when the CP on the (RDP) target machine is loaded. So we do not repeat the first step (triggering the token for a new transactionid) in RDP scenarios, since we already have the authentication to submit to windows, we just need to verify the second factor.

I will fix/improve this for next version. Until then you will have restart the RDP connection to trigger again or use token without challenge-response.

One of the following options could improve this behavior:
* Reset the CP completly in RDP and prefill the password so that the user only has to press enter again. (Requires decryption of the password before prefilling so that the length of `*`'s matches the actual password and does not confuse the user).
 This would reflect the local login behavior but is kind of unneccessary/unintuitive because the windows authentication is already completed.
* Automate the above - possibly introduces more RDP specific logic for the **whole** process
* Add option in 2nd step to retrigger - is only useful for RDP since in local logins we do not know if the windows password is correctly beforehand
