### ISSUE TITLE
Connection indicator

### ISSUE THREAD

**Issue by adazlord** [privacyidea/privacyidea-credential-provider#159]
Hi,

We are using AOVPN (device tunnel) for home office laptops, and this tunnel is only for the PI connection. It automatically connects when the internet is reachable.
My problem is that the user has no feedback about the connection to the PI server. There should be a small red/green circle (eg in the corner of the logo) indicating whether the PrivacyIDEA server is currently available or not.

Is it possible in the near future?

Thank you,
Adaz

**Comment by nilsbehlen** [comment]
Hi,
what logo do mean? The image in the center?
While i like your idea, the problem is that the Credential Provider interface is not very flexible in terms of the UI (you can not simply draw a red or green circle somewhere). The logo in the center is a customizable (by specifying the path) bitmap, so we would need 2 bitmaps, one for each availibility status. Or we can add a text at the bottom or something.

**Comment by adazlord** [comment]
Hi Nils,
Thank you for your reply!
Yes, I meant the image in the middle, but it's not important to display a circle there. Two bitmaps should be fine, or a text at the bottom. The only point would be to see the status of the connection.
When do you think this could be solved and with how much work?

**Comment by nilsbehlen** [comment]
We are currently not working on this project. The next cycle will probably be in 1.5-2 months

**Comment by nilsbehlen** [comment]
Unfortunately i do not think this can be done in a useful way with the limitations that are given by the credential provider interface from windows.
