### ISSUE TITLE
Configure in which scenarios the cp is enabled

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea-credential-provider#68]
Define a registry entry that allows to configure in which scenarios the cp should be enabled.
Having a remote session should be considered aswell.

Currently the scenarios **LOGON, UNLOCK** and **CREDUI** (two step turned off automatically) are enabled by default.
**CHANGE_PASSWORD** seems unneccessary because it only covers the password change that is triggered by the user AFTER logon/unlock. If the password has to be changed because it is expired etc., the scenario is still UNLOCK or LOGON which is already covered.

The config entry could be:
* **0** - Both non-remote and remote.
* **1** - Non-remote only.
* **2** - Remote only.
* **3** - Disabled.

Where every scenario has a separate entry and if there is none, the default - enabled for both - is assumed.

Evaluation should be in CProvider::SetUsageScenario.

**Comment by cornelinux** [comment]
Do we currently ask during **CHANGE_PASSWORD**? Could we?

If a desktop was not locked and an attacker would go there and change the password since he knows the password of the user, but not the OTP, then the attacker can actually change the password. If we would also cover **CHANGE_PASSWORD** then we could assure, that the user can only change his password, if he has the 2nd factor available.

How about:

* 0 - disable
* 1 - Logon
* 2 - Unlock
* 4 - Credui
* 8 - change_password

Then, if for any reasons s.o. does not want a 2nd factor during unlock, only during login, this could be done.
The default would be ``7 = 1 + 2 + 4``  and could be extended to ``15`` or could be set to ``5``, if **UNLOCK** should not be protected by 2fa?

**Comment by nilsbehlen** [comment]
The filter has to be considered aswell: there could be configurations where there is no more cp left.

Moreover, the filter could be made configurable, which could be combined with the cp to the following extension of the config:

* **0**: fully enabled
* **0**:
* **0**:
